[project]
name = "busyboy"
version = "0.1.0"
description = "Console application to display various information on BUSYBar"
readme = "README.md"
authors = [
    { name = "Bence Molnár", email = "developer@molnarbence.dev" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
busyboy = "busyboy:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
