[project]
name = "busyboy"
version = "0.1.0"
description = "Console application to display various information on BUSYBar"
readme = "README.md"
authors = [
    { name = "Bence Molnár", email = "developer@molnarbence.dev" }
]
requires-python = ">=3.14"
dependencies = [
    "busylib",
    "click>=8.4.2",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
]

[project.scripts]
busyboy = "busyboy:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.1",
    "ty>=0.0.65",
]

[tool.uv.sources]
busylib = { git = "https://github.com/busy-app/busylib-py" }

##### TESTING #####

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]

[tool.coverage.run]
branch = true
source = ["src"]
relative_files = true

[tool.coverage.report]
exclude_also = [
    "if TYPE_CHECKING:", # imports / code here is executed during mypy tests.
]
fail_under = 75
precision = 2

[tool.coverage.xml]
output = "build/coverage.xml"

#### LINTING ###

[tool.ruff]
# Set the maximum line length
line-length = 120
exclude = [".git", "__pycache__", ".venv", "build", "dist", "*.egg-info"]


[tool.ruff.lint.isort]
force-sort-within-sections = true
split-on-trailing-comma = true

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.flake8-quotes]
# Use double quotes
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"
